[0m16:28:09.774260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022A9AB880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022D5887F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022D588A30>]}


============================== 16:28:09.779462 | 45e6011e-dcd4-416e-8681-7a12458a06d4 ==============================
[0m16:28:09.779462 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:28:09.780244 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\garrett.becker\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init ae-bootcamp', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:28:09.806552 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/garrett.becker/.dbt')}
[0m16:28:09.807524 [info ] [MainThread]: Creating dbt configuration folder at 
[0m16:28:51.935601 [debug] [MainThread]: Starter project path: C:\Users\garrett.becker\Documents\PersonalLearning\Udemy Courses\AnalyticsEngineeringBootcamp\NorthwindWarehouseProject\venv\lib\site-packages\dbt\include\starter_project
[0m16:28:52.016340 [info ] [MainThread]: 
Your new dbt project "analyticsengineeringbootcamp24" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:28:52.019335 [info ] [MainThread]: Setting up your profile.
[0m16:30:41.944271 [info ] [MainThread]: Profile analyticsengineeringbootcamp24 written to C:\Users\garrett.becker\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:30:41.946268 [debug] [MainThread]: Command `dbt init` succeeded at 16:30:41.946268 after 152.28 seconds
[0m16:30:41.947262 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022A9AB880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022D5887F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022D5FC3A0>]}
[0m16:30:41.948259 [debug] [MainThread]: Flushing usage events
[0m12:07:40.450251 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D81DBB8B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D849997F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D84999A00>]}


============================== 12:07:40.456028 | b7b1c890-3969-4119-9dec-2256933599d3 ==============================
[0m12:07:40.456028 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:07:40.457028 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\garrett.becker\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:07:40.500044 [info ] [MainThread]: dbt version: 1.8.3
[0m12:07:40.501016 [info ] [MainThread]: python version: 3.9.7
[0m12:07:40.501016 [info ] [MainThread]: python path: C:\Users\garrett.becker\Documents\PersonalLearning\Udemy Courses\AnalyticsEngineeringBootcamp\NorthwindWarehouseProject\venv\Scripts\python.exe
[0m12:07:40.502132 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m12:07:48.326719 [info ] [MainThread]: Using profiles dir at C:\Users\garrett.becker\.dbt
[0m12:07:48.327986 [info ] [MainThread]: Using profiles.yml file at C:\Users\garrett.becker\.dbt\profiles.yml
[0m12:07:48.328891 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\garrett.becker\Documents\PersonalLearning\Udemy Courses\AnalyticsEngineeringBootcamp\NorthwindWarehouseProject\dbt_project.yml
[0m12:07:48.329889 [info ] [MainThread]: adapter type: bigquery
[0m12:07:48.329889 [info ] [MainThread]: adapter version: 1.8.2
[0m12:07:48.330920 [info ] [MainThread]: Configuration:
[0m12:07:48.331883 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m12:07:48.331883 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:07:48.332912 [info ] [MainThread]: Required dependencies:
[0m12:07:48.333878 [debug] [MainThread]: Executing "git --help"
[0m12:07:48.342854 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m12:07:48.343862 [info ] [MainThread]: Connection:
[0m12:07:48.344849 [info ] [MainThread]:   method: oauth
[0m12:07:48.344849 [info ] [MainThread]:   database: analyticsengineeringbootcamp24
[0m12:07:48.346154 [info ] [MainThread]:   execution_project: analyticsengineeringbootcamp24
[0m12:07:48.346844 [info ] [MainThread]:   schema: dbt_garrett
[0m12:07:48.347841 [info ] [MainThread]:   location: US
[0m12:07:48.348839 [info ] [MainThread]:   priority: interactive
[0m12:07:48.348839 [info ] [MainThread]:   maximum_bytes_billed: None
[0m12:07:48.349838 [info ] [MainThread]:   impersonate_service_account: None
[0m12:07:48.350932 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m12:07:48.351861 [info ] [MainThread]:   job_retries: 1
[0m12:07:48.351861 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m12:07:48.352828 [info ] [MainThread]:   job_execution_timeout_seconds: 300
[0m12:07:48.353825 [info ] [MainThread]:   timeout_seconds: 300
[0m12:07:48.353825 [info ] [MainThread]:   client_id: None
[0m12:07:48.354822 [info ] [MainThread]:   token_uri: None
[0m12:07:48.354822 [info ] [MainThread]:   dataproc_region: None
[0m12:07:48.355847 [info ] [MainThread]:   dataproc_cluster_name: None
[0m12:07:48.356818 [info ] [MainThread]:   gcs_bucket: None
[0m12:07:48.358812 [info ] [MainThread]:   dataproc_batch: None
[0m12:07:48.359810 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m12:07:48.359810 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m12:07:48.360808 [debug] [MainThread]: Opening a new connection, currently in state init
[0m12:07:48.382014 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m12:07:48.383041 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m12:07:48.384020 [info ] [MainThread]: [31m3 checks failed:[0m
[0m12:07:48.385004 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\garrett.becker\Documents\PersonalLearning\Udemy Courses\AnalyticsEngineeringBootcamp\NorthwindWarehouseProject\dbt_project.yml> not found

[0m12:07:48.386001 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m12:07:48.386998 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m12:07:48.390717 [debug] [MainThread]: Command `dbt debug` failed at 12:07:48.390717 after 8.05 seconds
[0m12:07:48.391502 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m12:07:48.392036 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D81DBB8B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8756A1C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D87B06AC0>]}
[0m12:07:48.392527 [debug] [MainThread]: Flushing usage events
[0m12:08:10.520249 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D53FCCCD60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D5428ABA00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D5428AB7F0>]}


============================== 12:08:10.524369 | 3494e794-6843-4bfb-831d-dbbcc6300892 ==============================
[0m12:08:10.524369 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:08:10.525790 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\garrett.becker\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:08:10.526723 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\garrett.becker\Documents\PersonalLearning\Udemy Courses\AnalyticsEngineeringBootcamp\NorthwindWarehouseProject\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:08:10.528685 [debug] [MainThread]: Command `dbt run` failed at 12:08:10.528685 after 0.12 seconds
[0m12:08:10.529251 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D53FCCCD60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D5428AB700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D5428ABA30>]}
[0m12:08:10.529683 [debug] [MainThread]: Flushing usage events
